apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
      - name: mern-backend
        image: ku2972000/mern-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

        # 🔐 Environment variables from Kubernetes Secret
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mern-secret
              key: MONGO_URI