apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
spec:
  replicas: 1

  selector:
    matchLabels:
      app: mern-backend

  template:
    metadata:
      labels:
        app: mern-backend

    spec:
      containers:
      - name: mern-backend

        image: kushaldevopsengg/mern-backend:v1

        imagePullPolicy: Always

        ports:
        - containerPort: 5000

        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3

        env:
        - name: MONGO_URI
          valueFrom:
           secretKeyRef:
             name: mern-secret
             key: MONGO_URI
