name: CI/CD - Build, Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3️⃣ Set unique image tag
      - name: Set Image Tag
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # 4️⃣ Build image
      - name: Build Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-backend:$TAG ./backend

      # 5️⃣ Push image
      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-backend:$TAG

      # 6️⃣ Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      # 7️⃣ Configure kubeconfig
      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      # 8️⃣ Deploy to Kubernetes
      - name: Update Deployment
        run: |
          kubectl set image deployment/mern-backend \
          mern-backend=${{ secrets.DOCKER_USERNAME }}/mern-backend:$TAG

      # 9️⃣ Verify rollout
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/mern-backend