name: CI - Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 🔥 SET UNIQUE IMAGE TAG
      - name: Set Image Tag
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # 🐳 BUILD IMAGE WITH TAG
      - name: Build Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-backend:$TAG ./backend

      # 📤 PUSH IMAGE
      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mern-backend:$TAG